spring.application.name=Lab2
server.port=8081
greeting.message=Hello from Lab2!

management.endpoints.web.exposure.include=health,info,metrics,env,threaddump,heapdump,prometheus

management.endpoint.health.show-details=always

info.app.name=Demo App
info.app.version=0.1.0
info.app.owner=Florin