spring.datasource.url=jdbc:postgresql://localhost:5432/lab5
spring.datasource.username=java
spring.datasource.password=java

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true