spring.datasource.url=jdbc:postgresql://localhost:5432/lab5
spring.datasource.username=java
spring.datasource.password=java

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.security.filter.dispatcher-types=request,async,error

app.security.jwt.secret=58WetneIa+xfwak2pGanPNwxjwox60mMroXTg5k1N98=
app.security.jwt.expiration=3600000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized