spring.application.name=Lab3

# Default discount strategy
discount.strategy=large-value

logging.level.com.example.Lab3=DEBUG
logging.level.org.springframework.context.event=DEBUG
logging.level.org.aspectj=DEBUG
