spring.application.name=StableMatch

server.port=8081

# Resilience4j Configuration
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=1000
resilience4j.retry.configs.default.enableExponentialBackoff=true
resilience4j.retry.configs.default.exponentialBackoffMultiplier=2

resilience4j.retry.instances.stableMatchRetry.baseConfig=default
resilience4j.retry.instances.stableMatchRetry.maxAttempts=3

resilience4j.retry.instances.defaultRetry.baseConfig=default

# TimeLimiter Configuration
resilience4j.timelimiter.configs.default.timeoutDuration=5000
resilience4j.timelimiter.instances.stableMatchTimeout.timeoutDuration=5000

# Logging
logging.level.com.example.Lab8=INFO
logging.level.io.github.resilience4j=DEBUG
